Romaric

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -34,9 +34,12 @@ jobs:
         run: make clean
       - name: Check executables
         run: |
-          if [ -f $EXECUTABLES ]; then
-            exit 1
-          fi
+          for executable in $EXECUTABLES; do
+            if [ ! -x "$executable" ]; then
+              echo "Error: $executable not found or not executable"
+              exit 1
+            fi
+          done
   run_tests:
     runs-on: ubuntu-latest
     needs: check_program_compilation
