[+] meric

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,90 +1,82 @@
 name: chocolatine
 on:
-  push:
-    branches-ignore:
-      - "ga-ignore-*"
-  pull_request:
-    branches-ignore:
-      - "ga-ignore-*"
+    push:
+      branches-ignore: 
+         -  'ga-ignore-*'
+    pull_request:
+        branches-ignore: 
+         -  'ga-ignore-*'
+
 env:
-  MIRROR_URL: "git@github.com:EpitechPGEPromo2029/B-DOP-200-COT-2-1-chocolatine-joachim.goeh-akue.git"
-  EXECUTABLES: "202unsold"
+    MIRROR_URL: "B-PSU-100-COT-1-1-myls-meric.gbemetonou" #${{vars.MIRROR_URL}}
+    EXECUTABLES: "my_ls" #${{vars.EXECUTABLES}}
+
 jobs:
-  # check_coding_style:
-  #   name: Vérification du coding style
-  #   runs-on: ubuntu-latest
-  #   container: ghcr.io/epitech/coding-style-checker:latest
-  #   steps:
-  #     - name: Cloner le dépôt
-  #       uses: actions/checkout@v4
-  #     - name: Exécuter le vérificateur de coding style
-  #       run: check.sh $(pwd) $(pwd)
-  #     - name: Analyser les erreurs
-  #       run: |
-  #         if [ -f coding-style-reports.log ] && [ -s coding-style-reports.log ]; then
-  #           cat coding-style-reports.log
-  #           while IFS= read -r line; do
-  #             echo "::error file=$(echo "$line" | cut -d':' -f1),line=$(echo "$line" | cut -d':' -f2),title=Coding Style Error::$line"
-  #           done < coding-style-reports.log
-  #           exit 1
-  #         else
-  #           echo "Aucune erreur de coding style détectée ou aucun fichier C trouvé."
-  #         fi
-  check_program_compilation:
-    name: "Check Program Compilation"
-    runs-on: ubuntu-latest
-    # needs: check_coding_style
-    container: epitechcontent/epitest-docker
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-      - name: Clean Previous Builds
-        run: make fclean
-      - name: Compile the Project
-        run: make
-        timeout-minutes: 2
-      - name: Clean the Project
-        run: make clean
-      - name: Verify Executables
-        run: |
-          bash -c '
-          IFS="," read -ra EXEC_FILES <<< "$(echo "$EXECUTABLES" | tr "," "\n")"
-          for file in "${EXEC_FILES[@]}"; do
-            if [[ ! -x "$file" ]]; then
-              echo "::error file=$file::Executable not found or not executable"
-              exit 1
-            else
-              echo "$file est bien un exécutable."
-            fi
-          done
-          '
-  run_tests:
-    name: "Run Tests"
-    runs-on: ubuntu-latest
-    needs: check_program_compilation
-    container: epitechcontent/epitest-docker
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-      - name: Run Project Tests
-        run: |
-          if make tests_run; then
-            echo "Tous les tests sont passés."
-          else
-            echo "::error title=Tests échoués::Un ou plusieurs tests ont échoué."
-            exit 1
-          fi
-        timeout-minutes: 2
-  push_to_mirror:
-    name: "Push to Mirror"
-    runs-on: ubuntu-latest
-    needs: run_tests
-    if: github.event_name == 'push'
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-      - name: Mirror Repository
-        uses: pixta-dev/repository-mirroring-action@v1
-        with:
-          target_repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+    check_coding_style:
+        runs-on: ubuntu-latest
+        container: ghcr.io/epitech/coding-style-checker:latest
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4
+              with:
+                fetch-depth: 0
+            - run: check.sh $(pwd) $(pwd)
+            - run:  ls
+            - run: |
+                fileName="coding-style-reports.log"
+                content=$(cat "$fileName")
+                echo "$content"
+    check_program_compilation:
+      runs-on: ubuntu-latest
+      container: epitechcontent/epitest-docker
+      needs: check_coding_style
+      steps:
+        - name: Checkout
+          uses: actions/checkout@v4
+        - name: Compile the project  
+          run: make
+          timeout-minutes: 2
+        - name: Clean the repo  
+          run: make clean
+        - name: Check executables
+          run: |
+            for item in ${{vars.EXECUTABLES}}; do
+              if [ ! -x "$item" ]; then
+                echo "Compilation check failed."
+                 exit 1
+               fi
+            done
+
+    run_tests:
+        runs-on: epitechcontent/epitest-docker
+        needs: check_program_compilation
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v4
+        - name: Unit Tests
+          run: make tests_run
+    
+    push_to_mirror:
+        runs-on: ubuntu-latest
+        needs: run_tests
+        steps:
+            - uses: actions/checkout@v3
+            - uses: pixta-dev/repository-mirroring-action@v1
+              with:
+                target_repo_url:
+                    ${{vars.MIRROR_URL}}
+                ssh_private_key:
+                    ${{ secrets.GITHUB_SSH_PRIVATE_KEY }}
+    
+    library_checkor:
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v3
+            - run: |
+                ls | grep -q ".a" > f
+                if [ -s f ]; then
+                    echo "The lib is really there."
+                else
+                    echo "Lib not found. May be you don't need a library."
+                    exit 1
+                fi
