[+] Delor

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,73 +1,25 @@
-name: Choco Workflow
- 
+name: Chocolatine
 on:
   push:
-    branches:
-      - "**"
-      - "! ga-ignore-"
+    branches-ignore:
+      - " ga-ignore-"
   pull_request:
-    branches:
-      - "**"
-      - "! ga-ignore-"
-    
-env:
-  MIRROR_URL: ${{ secrets.MIRROR_URL }}
-  EXECUTABLES: "cqq"
- 
+    branches-ignore:
+      - " ga-ignore-"
+
 jobs:
-  coding_style:
+  check_coding_style:
     runs-on: ubuntu-latest
     container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - name: checkout repo
-        uses: actions/checkout@v4
- 
-      - name: check coding style
-        run: |
-          check.sh $(pwd) $(pwd)
-          if [ -f coding-style-report.log ]; then
-            cat coding-style-reports.log
-            exit 84
-          fi
- 
-  rigth_compilation:
+      - uses: actions/checkout@v4
+      - run: check.sh $(pwd) $(pwd)
+
+  check_program_compilation:
+    needs: check_coding_style
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker
-    needs: coding_style
     steps:
-      - name: checkout repo
-        uses: actions/checkout@v4
-      
-      - name: code compilation
-        run: make
-        timeout-minutes: 2
- 
-      - name: clean the repo
-        run: make clean
- 
-      - name: existing of the binary
-        run: |
-             make
-             for exe in $(echo $EXECUTABLES | tr "," " "); do
-             if [ ! -x $exe ]; then
-             echo "::eror file=$exe, line=1::Executables $exe is missing"
-             exit 1
-             fi
-             done
- 
-      - name: clen repectorie
-        run: make clean
- 
-  # push_to_mirror:
-  #   runs-on: ubuntu-latest
-  #   needs: rigth_compilation
-  #   if: github.event_name == 'push'
-  #   steps:
-  #     - name: checkout
-  #       uses: actions/checkout@v4
- 
-  #     - name: push to miror repo
-  #       uses: pixta-dev/repository-mirroring-action@v1
-  #       with:
-  #         ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
-  #         destination_repo: ${{ env.MIRROR_URL }}
+      - uses: actions/checkout@v4
+      - run: make || { echo "compilation failed"; exit 84; }
+      - run: make clean
