[+] Amyrath

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,97 +1,106 @@
-name: Chocolatine Workflow
-
+name: chocolatine
 on:
   push:
     branches-ignore:
-      - 'ga-ignore**'
+       - 'ga-ignore-*'
   pull_request:
     branches-ignore:
-      - 'ga-ignore**'
+       - 'ga-ignore-*'
 
 env:
-  MIRROR_URL: ${{ secrets.MIRROR_URL }}
-  EXECUTABLES: ${{ secrets.EXECUTABLES }}
+  MIRROR_URL: git@github.com:amyrath/try_chocolatine.git
+  EXECUTABLES: mysh
+  BANNED_FUNCTIONS: printf,strcmp,puts,strncmp,strlen,fgets,fputs,fprintf,strtok
+  LIBRARIES: $(lib)
+
 
 jobs:
   check_coding_style:
-    name: Check coding style
     runs-on: ubuntu-latest
-    if: github.repository != env.MIRROR_URL
     container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - name: Checkout repository
+      - name: checkout the repository
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      
-      - name: Run coding style checker
+      - name: chech coding style
+        run: check.sh $(pwd) $(pwd)
+      - name: verify the coding style file
         run: |
-          check.sh $(pwd) $(pwd)
-          if [ -f coding-style-reports.log ]; then
-            while IFS= read -r line; do
-              echo "::error file=${line%:},line=${line#:}::${line#::}"
-            done < coding-style-reports.log
+          if [coding-style-reports.log]; then
+            cat coding-style-reports.log
             exit 1
           fi
 
   check_program_compilation:
-    name: Check program compilation
     needs: check_coding_style
     runs-on: ubuntu-latest
-    if: github.repository != env.MIRROR_URL
     container: epitechcontent/epitest-docker
     steps:
-      - name: Checkout repository
+      - name: checkout the repository
         uses: actions/checkout@v4
-      
-      - name: Make
+      - name: check the compilation
         run: make
         timeout-minutes: 2
-      
-      - name: Verify executables
+      - name: clean the repot
+        run: make clean
+      - name: control executable
         run: |
-          IFS=',' read -ra EXEC_ARRAY <<< "$EXECUTABLES"
-          for exec in "${EXEC_ARRAY[@]}"; do
-            if [ ! -f "$exec" ]; then
-              echo "::error file=$exec::Executable $exec was not generated by make"
+          for exe in $(echo $EXECUTABLES); do
+            if [! -x "$exe"]; then
+              echo "execution is fail"
               exit 1
+            else
+              echo "$executable is working"
             fi
-            if [ ! -x "$exec" ]; then
-              echo "::error file=$exec::File $exec exists but is not executable"
+          done
+
+  run_tests:
+    needs: check_program_compilation
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    steps:
+       - name: checkout the repository
+         uses: actions/checkout@v4
+       - name: check the unit tests
+         run: make tests_run
+         timeout-minutes: 2
+
+  banned_functions:
+    needs: run_tests
+    runs-on: ubuntu-latest
+    steps:
+       - name: Checkout repository
+         uses: actions/checkout@v4
+       - name: check the banned functions
+         run: |
+          if grep -rn "(${{ env.BANNED_FUNCTIONS }})" --include=\*.c; then
+            echo "Banned function"
+            exit 1
+          fi
+
+  push_to_mirror:
+    needs: banned_functions
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout the repository
+        uses: actions/checkout@v4
+      - name: create the key
+        run: |
+          mkdir ~/.ssh
+          echo "$GIT_SSH_PRIVATE_KEY" > ~/.ssh/stock
+          chmod 600 ~/.ssh/stock
+
+  check_libraries:
+    runs-on: ubuntu-latest
+    needs: push_to_mirror
+    steps:
+      - name: Checkout the repository
+        uses: actions/checkout@v4
+      - name: Verify compiled libraries
+        run: |
+         read -ra LIBS <<< ${{ env.LIBRARIES }}
+          for lib in "${LIBS[@]}"; do
+            if [ ! -f "$lib" ]; then
+              echo "include file=$lib"
               exit 1
             fi
           done
-      
-      - name: Make clean
-        run: make clean
-
-  run_tests:
-    name: Run tests
-    needs: check_program_compilation
-    runs-on: ubuntu-latest
-    if: github.repository != env.MIRROR_URL
-    container: epitechcontent/epitest-docker
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      
-      - name: Run tests
-        run: make tests_run
-        timeout-minutes: 2
-
-  push_to_mirror:
-    name: Push to mirror repository
-    needs: run_tests
-    if: github.event_name == 'push' && github.repository != env.MIRROR_URL
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      
-      - name: Mirror repository
-        uses: pixta-dev/repository-mirroring-action@v1
-        with:
-          target_repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
