[+] mohamed

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,83 +1,77 @@
-name: Chocolatine_Workflow
+name: Chocolatine
 on:
   push:
     branches-ignore:
-    - "ga-ignore-*"
+      - ga-ignore-*
   pull_request:
     branches-ignore:
-    - "ga-ignore-*"
+      - ga-ignore-*
 env:
-  EXECUTABLES: mysh, 202unsold
+  MIRROR_URL: "git@github.com:mhdadn04/chocolatin.git"
+  EXECUTABLES: "mysh"
 
 jobs:
-  # check_coding_style:
-  #   runs-on: ubuntu-latest
-  #   container: ghcr.io/epitech/coding-style-checker:latest
-  #   steps:
-  #   - name: Checkout GH repository
-  #     uses: actions/checkout@v4
-  #     with:
-  #       repository: ${{ github.repository }}
-
-  #   - name: Run coding-style checker script
-  #     run: check.sh $(pwd) $(pwd)
-
-  #   - name: Display coding style errors as annotations if any errors
-  #     id: annotations
-  #     run: |
-  #       if [ ! -f coding-style-reports.log ]; then
-  #         echo "No coding style report found."
-  #         exit 1
-  #       fi
-
-  #       NB_ERRORS=$(cat coding-style-reports.log | wc -l)
-  #       if [ $NB_ERRORS -ge 1 ]; then
-  #         while IFS= read -r line
-  #         do
-  #           FILE=$(echo $line | cut -d ':' -f1)
-  #           LINE=$(echo $line | cut -d ':' -f2)
-  #           ERROR=$(echo $line | cut -d ':' -f3-)
-  #           FILE=$(realpath --relative-to=$(pwd) $FILE)
-  #           echo "::error file=$FILE,line=$LINE,title=$NB_ERRORS coding style errors found::$ERROR"
-  #         done < coding-style-reports.log
-  #         exit 1
-  #       fi
-  #       exit 0
+  checking_the_coding_style:
+    name: Check the coding style
+    runs-on: ubuntu-latest
+    container: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: check the repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 1
+      - name: run coding style
+        run: check.sh $(pwd) $(pwd)
+      - name: report coding style checking
+        if: failure()
+        run: cat coding-style-reports.log && exit 1
 
   check_program_compilation:
+    name: Check program compilation
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker:latest
-    # needs: check_coding_style
+    needs: checking_the_coding_style
     steps:
-    - name: Checkout GH repository
-      uses: actions/checkout@v4
-      with:
-        repository: ${{ github.repository }}
-
-    - name: Compile the project
-      run: make
-      timeout-minutes: 2
-
-    - name: Check if the executable exists
-      run: |
-        if [ ! -f ${{ env.EXECUTABLES }} ]; then
-          echo "The executable ${{ env.EXECUTABLES }} does not exist."
-        exit 1
-        fi
-
-    - name: Clean the project
-      run: make fclean
+      - name: check repository
+        uses: actions/checkout@v4
+      - name: program's compilation
+        run: make
+        timeout-minutes: 2
+      - name: clean repository
+        run: make clean
+      - name: Verify binaries
+        run: |
+          IFS=','
+          set -- $EXECUTABLES
+          for i in "$@"; do
+            if [ ! -x "$i" ]; then
+              echo "Missing or non-executable file $i"
+              exit 1
+            fi
+          done
 
   run_tests:
+    name: run tests
     runs-on: ubuntu-latest
-    container: epitechcontent/epitest-docker
-    # needs: check_program_compilation
+    container: epitechcontent/epitest-docker:latest
+    needs: check_program_compilation
     steps:
-    - name: Checkout GH repository
-      uses: actions/checkout@v4
-      with:
-        repository: ${{github.repository}}
+      - name: check repository
+        uses: actions/checkout@v4
+      - name: run tests
+        run: make tests_run
+        timeout-minutes: 2
 
-    - name: Launch unit_tests
-      run: make tests_run
-      timeout-minutes: 2
+  push_to_mirror:
+    name: Push to mirror
+    runs-on: ubuntu-latest
+    needs: run_tests
+    if: github.event_name == 'push'
+    steps:
+      - name: check repository
+        uses: actions/checkout@v4
+      - name: Mirroring
+        uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url: ${{ env.MIRROR_URL }}
+          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
