[+] Amyrath

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,106 +1,73 @@
-name: chocolatine
+name: Choco Workflow
+ 
 on:
   push:
-    branches-ignore:
-       - 'ga-ignore-*'
+    branches:
+      - "**"
+      - "! ga-ignore-"
   pull_request:
-    branches-ignore:
-       - 'ga-ignore-*'
-
+    branches:
+      - "**"
+      - "! ga-ignore-"
+    
 env:
-  MIRROR_URL: git@github.com:amyrath/try_chocolatine.git
-  EXECUTABLES: mysh
-  BANNED_FUNCTIONS: printf,strcmp,puts,strncmp,strlen,fgets,fputs,fprintf,strtok
-  LIBRARIES: $(lib)
-
-
+  MIRROR_URL: ${{ secrets.MIRROR_URL }}
+  EXECUTABLES: "mysh"
+ 
 jobs:
-  check_coding_style:
+  coding_style:
     runs-on: ubuntu-latest
     container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - name: checkout the repository
+      - name: checkout repo
         uses: actions/checkout@v4
-      - name: chech coding style
-        run: check.sh $(pwd) $(pwd)
-      - name: verify the coding style file
+ 
+      - name: check coding style
         run: |
-          if [coding-style-reports.log]; then
+          check.sh $(pwd) $(pwd)
+          if [ -f coding-style-report.log ]; then
             cat coding-style-reports.log
-            exit 1
+            exit 84
           fi
-
-  check_program_compilation:
-    needs: check_coding_style
+ 
+  rigth_compilation:
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker
+    needs: coding_style
     steps:
-      - name: checkout the repository
+      - name: checkout repo
         uses: actions/checkout@v4
-      - name: check the compilation
+      
+      - name: code compilation
         run: make
-        timeout-minutes: 2
-      - name: clean the repot
+        timeout: 120
+ 
+      - name: clean the repo
         run: make clean
-      - name: control executable
+ 
+      - name: existing of the binary
         run: |
-          for exe in $(echo $EXECUTABLES); do
-            if [! -x "$exe"]; then
-              echo "execution is fail"
-              exit 1
-            else
-              echo "$executable is working"
-            fi
-          done
-
-  run_tests:
-    needs: check_program_compilation
-    runs-on: ubuntu-latest
-    container: epitechcontent/epitest-docker
-    steps:
-       - name: checkout the repository
-         uses: actions/checkout@v4
-       - name: check the unit tests
-         run: make tests_run
-         timeout-minutes: 2
-
-  banned_functions:
-    needs: run_tests
-    runs-on: ubuntu-latest
-    steps:
-       - name: Checkout repository
-         uses: actions/checkout@v4
-       - name: check the banned functions
-         run: |
-          if grep -rn "(${{ env.BANNED_FUNCTIONS }})" --include=\*.c; then
-            echo "Banned function"
-            exit 1
-          fi
-
-  push_to_mirror:
-    needs: banned_functions
-    runs-on: ubuntu-latest
-    steps:
-      - name: checkout the repository
-        uses: actions/checkout@v4
-      - name: create the key
-        run: |
-          mkdir ~/.ssh
-          echo "$GIT_SSH_PRIVATE_KEY" > ~/.ssh/stock
-          chmod 600 ~/.ssh/stock
-
-  check_libraries:
-    runs-on: ubuntu-latest
-    needs: push_to_mirror
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
-      - name: Verify compiled libraries
-        run: |
-         read -ra LIBS <<< ${{ env.LIBRARIES }}
-          for lib in "${LIBS[@]}"; do
-            if [ ! -f "$lib" ]; then
-              echo "include file=$lib"
-              exit 1
-            fi
-          done
+             make
+             for exe in $(echo $EXECUTABLES | tr "," " "); do
+             if [ ! -x $exe ]; then
+             echo "::eror file=$exe, line=1::Executables $exe is missing"
+             exit 1
+             fi
+             done
+ 
+      - name: clen repectorie
+        run: make clean
+ 
+    push to mirror:
+        runs-on: ubuntu-latest
+        needs: run_tests
+        if: github.event_name == 'push'
+        steps:
+          - name: checkout
+            uses: actions/checkout@v4
+ 
+          - name: push to miror repo
+            uses: pixta-dev/repository-mirroring-action@v1
+            with:
+                ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+                destination_repo: ${{ env.MIRROR_URL }}
