[+] jean victor

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -10,44 +10,44 @@ env:
   EXECUTABLES: 'mysh'
 
 jobs:
-  check_coding_style:
-    runs-on: ubuntu-latest
-    container: ghcr.io/epitech/coding-style-checker:latest
-    steps:
-    - name: Checkout GH repository
-      uses: actions/checkout@v4
-      with:
-        repository: ${{ github.repository }}
+  # check_coding_style:
+  #   runs-on: ubuntu-latest
+  #   container: ghcr.io/epitech/coding-style-checker:latest
+  #   steps:
+  #   - name: Checkout GH repository
+  #     uses: actions/checkout@v4
+  #     with:
+  #       repository: ${{ github.repository }}
 
-    - name: Run coding-style checker script
-      run: check.sh $(pwd) $(pwd)
+  #   - name: Run coding-style checker script
+  #     run: check.sh $(pwd) $(pwd)
 
-    - name: Display coding style errors as annotations if any errors
-      id: annotations
-      run: |
-        if [ ! -f coding-style-reports.log ]; then
-          echo "No coding style report found."
-          exit 1
-        fi
+  #   - name: Display coding style errors as annotations if any errors
+  #     id: annotations
+  #     run: |
+  #       if [ ! -f coding-style-reports.log ]; then
+  #         echo "No coding style report found."
+  #         exit 1
+  #       fi
 
-        NB_ERRORS=$(cat coding-style-reports.log | wc -l)
-        if [ $NB_ERRORS -ge 1 ]; then
-          while IFS= read -r line
-          do
-            FILE=$(echo $line | cut -d ':' -f1)
-            LINE=$(echo $line | cut -d ':' -f2)
-            ERROR=$(echo $line | cut -d ':' -f3-)
-            FILE=$(realpath --relative-to=$(pwd) $FILE)
-            echo "::error file=$FILE,line=$LINE,title=$NB_ERRORS coding style errors found::$ERROR"
-          done < coding-style-reports.log
-          exit 1
-        fi
-        exit 0
+  #       NB_ERRORS=$(cat coding-style-reports.log | wc -l)
+  #       if [ $NB_ERRORS -ge 1 ]; then
+  #         while IFS= read -r line
+  #         do
+  #           FILE=$(echo $line | cut -d ':' -f1)
+  #           LINE=$(echo $line | cut -d ':' -f2)
+  #           ERROR=$(echo $line | cut -d ':' -f3-)
+  #           FILE=$(realpath --relative-to=$(pwd) $FILE)
+  #           echo "::error file=$FILE,line=$LINE,title=$NB_ERRORS coding style errors found::$ERROR"
+  #         done < coding-style-reports.log
+  #         exit 1
+  #       fi
+  #       exit 0
 
   check_program_compilation:
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker:latest
-    needs: check_coding_style
+    # needs: check_coding_style
     steps:
     - name: Checkout GH repository
       uses: actions/checkout@v4
