Perault

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,107 +1,86 @@
-name: Chocolatine Workflow
-
-env:
-  MIRROR_URL: ${{ secrets.MIRROR_REPOSITORY }}
-  EXECUTABLES: "directory1/executableA,directory2/executableB"
+name: chocolatine
 
 on:
   push:
-    branches:
-      - '*'
-    paths-ignore:
-      - 'ga-ignore-**'
+	branches-ignore:
+  	"ga-ignore-*"
   pull_request:
-    branches:
-      - '*'
-    paths-ignore:
-      - 'ga-ignore-**'
+	branches-ignore:
+  	"ga-ignore-*"
+
+
+env:
+  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-1-chocolatine-mawunam.megnassan.git"
+  EXECUTABLES: "202unsold"
 
 jobs:
-  check_branch:
-    runs-on: ubuntu-latest
-    outputs:
-      run_job: ${{ steps.check_mirror.outputs.run_job }}
-
-    steps:
-      - name: Check if branch should be ignored
-        id: check_mirror
-        run: |
-          if [[ "${{ github.repository }}" == "${{ secrets.MIRROR_REPOSITORY }}" ]]; then
-            echo "::set-output name=run_job::false"
-          elif [[ "${{ github.ref }}" == refs/heads/ga-ignore-* ]]; then
-            echo "::set-output name=run_job::false"
-          else
-            echo "::set-output name=run_job::true"
-          fi
-
   check_coding_style:
-    needs: check_branch
-    if: ${{ needs.check_branch.outputs.run_job == 'true' }}
-    runs-on: ubuntu-latest
+	runs-on: ubuntu-latest
+	container:
+  	image: ghcr.io/epitech/coding-style-checker:latest
 
-    container:
-      image: ghcr.io/epitech/coding-style-checker:latest
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Run coding style checker
-        run: check.sh $(pwd) $(pwd)
+	steps:
+  	- uses: actions/checkout@v3
+    	run: |
+      	check.sh $(pwd) $(pwd)
+      	if grep -q "." "coding-style-reports.log"; then exit 1; else echo "No coding style issues found!"; fi/*.c
 
   check_program_compilation:
-    needs: check_coding_style
-    if: ${{ needs.check_branch.outputs.run_job == 'true' }}
-    runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker
+	runs-on: ubuntu-latest
+	container:
+  	image: epitechcontent/epitest-docker
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+	steps:
+  	- uses: actions/checkout@v3
 
-      - name: Build project
-        run: make
-        timeout-minutes: 2
+  	- name: Compile program
+    	run: make
+    	timeout-minutes: 2
 
-      - name: Clean up
-        run: make clean
+  	- name: Clean generated files
+    	run: make clean
 
-      - name: Verify executables
-        run: |
-          for executable in $(echo "${{ env.EXECUTABLES }}" | tr ',' '\n'); do
-            if [ ! -x "$executable" ]; then
-              echo "Error: $executable does not exist or is not executable"
-              exit 1
-            fi
-          done
-
+  	- name: Check executables
+    	run: |
+      	for executable in $EXECUTABLES; do
+        	if [[!-x "$executable" ]]; then
+          	echo "Missing or non-executable executable: $executable"
+          	exit 84
+        	fi
+      	done
+   	 
   run_tests:
-    needs: check_program_compilation
-    if: ${{ needs.check_branch.outputs.run_job == 'true' }}
-    runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker
+	runs-on: ubuntu-latest
+	container:
+  	image: epitechcontent/epitest-docker
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+	timeout-minutes: 2
 
-      - name: Run tests
-        run: make tests_run
-        timeout-minutes: 2
+	steps:
+  	- name: Checkout code
+    	uses: actions/checkout@v3
+
+  	- name: Run tests
+    	run: make tests_run
 
   push_to_mirror:
-    needs: run_tests
-    if: ${{ needs.check_branch.outputs.run_job == 'true' }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+	runs-on: ubuntu-latest
 
-      - name: Mirror repository
-        uses: pixta-dev/repository-mirroring-action@v1
-        with:
-          destination-url: ${{ env.MIRROR_URL }}
-          destination-branch: ${{ secrets.DESTINATION_BRANCH }}
-          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+	steps:
+  	- name: Checkout code
+    	uses: actions/checkout@v3
+
+  	- name: Push to mirror
+    	env:
+      	MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-1-chocolatine-mawunam.megnassan.git"
+      	GIT_SSH_PRIVATE_KEY: "SHA256:AfzpzHKoSSjDc5Pl18EoxOaa2MzC179ecEMre0dSW/Y"
+    	run: |
+      	# Configure Git with SSH key
+      	mkdir ~/.ssh
+      	echo "SHA256:AfzpzHKoSSjDc5Pl18EoxOaa2MzC179ecEMre0dSW/Y" > ~/.ssh/id_rsa
+      	chmod 600 ~/.ssh/id_rsa
+      	ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
+
+      	# Push to mirror repository
+      	git remote add mirror $MIRROR_URL
+      	git push mirror --all
