[+] Abayomi

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,25 +1,79 @@
-name: Chocolatine
+name: Chocolatine Workflow
+
 on:
   push:
-    branches-ignore:
-      - " ga-ignore-"
+    branches:
+      - '**'
+      - '!ga-ignore-**'
   pull_request:
-    branches-ignore:
-      - " ga-ignore-"
+    branches:
+      - '**'
+      - '!ga-ignore-**'
+
+env:
+  MIRROR_URL: ${{ secrets.MIRROR_URL }}
+  EXECUTABLES: "mysh"
+
 
 jobs:
   check_coding_style:
     runs-on: ubuntu-latest
     container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - uses: actions/checkout@v4
-      - run: check.sh $(pwd) $(pwd)
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
+      - name: Coding style checker run
+        run: |
+          check.sh $(pwd) $(pwd)
+          if [ -s coding-style-reports.log ]; then
+            cat coding-style-reports.log
+            exit 1
+          fi
+          
   check_program_compilation:
-    needs: check_coding_style
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker
+    needs: check_coding_style
     steps:
-      - uses: actions/checkout@v4
-      - run: make || { echo "compilation failed"; exit 84; }
-      - run: make clean
+      - name: Check repository
+        uses: actions/checkout@v3
+      - name: Project compile
+        run:  |
+              make
+              for exe in $(echo $EXECUTABLES); do
+              if [ ! -x $exe ]; then
+              echo "::error file=$exe,Executable $exe is missing or not executable"
+              exit 1
+              fi
+              done
+
+      - name: do clean
+        run: make clean
+
+  run_tests:
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    needs: check_program_compilation
+    timeout-minutes: 2
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Tests run
+        run: make tests_run
+
+  check_banned_functions:
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    needs: check_program_compilation
+    steps:
+      - name: Check repository
+        uses: actions/checkout@v3
+
+      - name: Check for banned functions
+        run: |
+          if grep -r "printf\|exit\strtok\|strlen\|strcmp|\snprintf\sprintf" src/; then
+            echo "::error::Banned functions found"
+            exit 84
+          fi
